### ISSUE TITLE
Move logs to /var/log/docker-registry-manager

### ISSUE THREAD

**Issue by snagles** [snagles/docker-registry-manager#109]

**Comment by neumayer** [comment]
Unless you have any strong reason to do this I'd suggest to.. not do this.

If the app is run in a docker container, docker will handle stdout/stderr.
If the app is run via systemd, systemd will handle stdout/stderr.
The docker/systemd combination will also handle log rotation of these logs.
If you don't write to files, you can't fill up the disk by writing to files.

**Comment by snagles** [comment]
Currently the logs are displayed in the UI by parsing the log.json file in the /app/logs folder, the proposal was to just move this from /app/logs to /var/log/docker-registry-manager. Logs are output both to stdout, and to the log.json file, so yes they would be duplicated in systemd/docker deployments. The log.json file can be deleted/archived from the interface if duplicated/size constraints are a concern.

If anyone has a cleaner proposal I'm happy to hear it

**Comment by neumayer** [comment]
If showing logs in the gui is a requirement, then it seems like a reasonable improvement -- given possible permission problems are solved properly without integrating with an init system.

My clean solution would still be not to display logs in the gui, stop logging to files, and focus on other stuff :-). Another option would be to have that behaviour behind a flag.
