### ISSUE TITLE
Q: Config.yml not being read.What am I doing wrong?

### ISSUE THREAD

**Issue by matsch01** [snagles/docker-registry-manager#116]
I have the following entry in my config.yml file, but it's not being read. I don't see any errors in the log. My registry is behind nginx with Lets Encrypt certs.

registries:
  myregistry:
    url: https://docker-registry.net
    username: username
    password: password
    refresh-rate: "5m"
    skip-tls: false

I'm running via docker-compose.

**Comment by snagles** [comment]
Hi,

This may be related to #114 . Are you using the encrypted password in the config.yml? I'm trying to narrow this down.

To attempted to reproduce with a registry using the below commands

```
htpasswd -cbB ./auth/htpasswd test test

docker run -d   -p 5000:5000   --restart=always   --name registry   -v `pwd`/auth:/auth   -e "REGISTRY_AUTH=htpasswd"   -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"   -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry:2

then in the config use test, test as the username and password
```

**Comment by matsch01** [comment]
Password is in plain text.

**Comment by snagles** [comment]
Does the connection to the registry work when you did the hostname as you mentioned in #117 ?

**Comment by matsch01** [comment]
Yes, adding my registry in the UI with these values does connect to the registry:

host: username:password@docker-registry.net
port: 443
HTTPS: true

There is a bug though. You must click the Registries menu item, then click your registry to right to access the registries. Clicking on Repositories returns a list of repos, but returns Page Not Found error when you click on one.

**Comment by snagles** [comment]
k, interesting, that helps. Thanks for the extra info

**Comment by snagles** [comment]
Could you paste the registry (from the registry itself, docker logs -f $REGISTRY_NAME) logs where it errors?

**Comment by snagles** [comment]
Are you requiring authentication in both nginx and the registry? Or is authentication managed only by nginx, and then unauthenticated is allowed to hit the registry itself?

**Comment by matsch01** [comment]
Authentication is only handled by nginx. Here is the [https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04](setup). 

I'm unclear what you are asking for regarding docker logs -f $REGISTRY_NAME).

**Comment by matsch01** [comment]
Logs for what scenario?

**Comment by snagles** [comment]
Errors for the invalid authentication, is nginx not even getting the passed user information? Does it make it through nginx and get denied at the registry itself? Those types of things.

I'll have some time tonight to setup a an environment using the guide you referenced. Everything seems to work fine in my testing using authentication in the registry itself. We can also take this to slack if you would be up to testing fixes

**Comment by matsch01** [comment]
To access the registry using this setup you must provide the username and password:

curl https://<YOUR_USERNAME>:<YOURPASSWORD>@[YOUR-DOMAIN]/v2/

So when I leave this off the username:password from the host in your UI, it's the same as:

curl https://YOUR-DOMAIN/v2/

I get a 401 error. I verified in the nginx logs.

**Comment by snagles** [comment]
The config.yml is currently the only supported way to set username/password, as posting the html form with user credentials in plain text (as you have seen) without tls seemed like a poor choice.

Basic authentication is sent in the header of each request when using the config.yml. When you supply credentials in that file it will automatically add the basic auth headers to each request. I'm trying to determine whether those headers are being set incorrectly, nginx is not accepting them, or if the registry itself is denying access.

**Comment by snagles** [comment]
After reading through this I think there was some confusion. I thought you managed to get the config.yml correctly passed through.

The config.yml is not getting passed correctly in via docker-compose, I'll push some fixes out tomorrow to fix this. As a temporary measure, if you update your docker-compose file to be 

```
version: '2'

services:
  docker-registry-manager:
    container_name: docker-registry-manager
    image: snagles/docker-registry-manager
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./config.yml:/opt/docker-registry-manager/config.yml"
```

and then run `docker stop docker-registry-manager && docker rm docker-registry-manager && docker rmi snagles/docker-registry-manager` and then `docker-compose up -d --build` it should parse the config.

**Comment by matsch01** [comment]
Working now. Thanks. I did have the following issues though:

Got the following per your instructions above:

WARNING: Image for service docker-registry-manager was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.

After running docker-compose up --build I got the following error:

docker-registry-manager    | time="2017-12-13T03:38:52Z" level=fatal msg="Failed to add registry (https://docker.eislan.net), invalid port: strconv.Atoi: parsing \"\": invalid syntax"

I had to add port 443 to the end of my host in config.yml. 

url: https://docker.eislan.net:443

Would be nice if you could assume 443 for https. Otherwise seems to be working.

**Comment by kelvinji2009** [comment]
@matsch01 My registry is also behind nginx with Lets Encrypt certs. But i always get `401`. Any idea?

**Comment by matsch01** [comment]
@kelvinji2009 Did you make the changes that snagles provided in his last comment?

**Comment by kelvinji2009** [comment]
@matsch01 Not yet. I use it with many other services. I will try it later. Thanks very much.

**Comment by kelvinji2009** [comment]
@snagles 
In default config tree,  the highest priority dir is $REPO_HOME and it maybe override the `opt` config dir.
```go
	// If the config path is not passed use the default project dir
	if configPath != "" {
		v.AddConfigPath(path.Dir(configPath))
		base := path.Base(configPath)
		ext := path.Ext(configPath)
		v.SetConfigName(base[0 : len(base)-len(ext)])
	} else {
		// use the default tree
		v.SetConfigName("config")
		v.AddConfigPath(conf.GOPATH + "/src/github.com/snagles/docker-registry-manager")
		v.AddConfigPath("../")
		v.AddConfigPath("/opt/docker-registry-manager")
	}
```

**Comment by kelvinji2009** [comment]
@matsch01 @snagles It works now after i overwrite the `/go/src/github.com/snagles/docker-registry-manager/app/config.yml` in my container.

**Comment by snagles** [comment]
This is now fixed. Do a fresh git clone and a docker-compose pull and everything should work as expected.
