### ISSUE TITLE
Q: How enter new repository that sits behind nginx with certificates.

### ISSUE THREAD

**Issue by matsch01** [snagles/docker-registry-manager#117]
When I enter my repo information via the UI, I have to include my username and password in the host field:

host: username:password@docker-registry.net
port: 443
HTTPS: true

But now my username and password are displayed everywhere the repo name is displayed.

I tried using the config.yml file, but it's not reading this file (see issue 116). Skip TLS has no effect.

How can I get access to my repo without having to include my username and password in the host?

**Comment by snagles** [comment]
Config.yml is the preferred method for adding. Adding via the UI is not supported until TLS is implemented
