### ISSUE TITLE
Clicking Repositories then a repository link results in page not found.

### ISSUE THREAD

**Issue by matsch01** [snagles/docker-registry-manager#120]
I'm running my repository behind nginx with certificates.

You fixed two issues related to this here [116](https://github.com/snagles/docker-registry-manager/issues/116) and here [117](https://github.com/snagles/docker-registry-manager/issues/117).

There is still one issue when accessing repositories via the Repositories menu item on left. This results in a Page Not Found error when clicking a repo link. The repos can however be accessed by going to Registries, clicking the repo pane, then clicking the repo link.

The url used in each case is different:

Via Repositories:
http://registry-manager:8080/registries/docker-registry.net:443

Via Registries:
http://registry-manager:8080/registries/docker-registry.net:443/repositories/reponame/tags

**Comment by snagles** [comment]
This should have been fixed in https://github.com/snagles/docker-registry-manager/commit/83fac39a126c97675aa8f9622ab361d26bf45e40, Assuming you're still using the git repository you'll need to do a ```git pull``` and then rebuild the image like in the other issue with ```docker-compose up --build```
