### ISSUE TITLE
Feature request: configuration by environment variables

### ISSUE THREAD

**Issue by delfer** [snagles/docker-registry-manager#132]
Hello! Thank you for nice project.

Can you please implement configuration by environment variables? For example:

- REPO_URL
- REPO_INSECURE
- REPO_USER
- REPO_PASSWORD
- UI_USER
- UI_PASSWORD

It's more useful when specify everything in docker-compose or kubernetes deployment yaml file instead of creation and uploading additional config files. Especially when docker registry configured in same file.

**Comment by snagles** [comment]
Hi Delfer,

This was already completed in the develop branch, which will be merged in in the next version release (https://github.com/snagles/docker-registry-manager/tree/develop#dockerfile and https://github.com/snagles/docker-registry-manager/blob/develop/docker-compose.yml). 

However, to maintain the ability to use multiple repositories (and maintain state) I intend for the registries.yml file to remain. REPO1_URL, REPO2_URL, REPO3_URL just didn't scale quite the way I liked and I wanted to simplify the configuration for all use cases.
