### ISSUE TITLE
The registry configuration needs a port even if the default SSL port

### ISSUE THREAD

**Issue by untergrundbiber** [snagles/docker-registry-manager#134]
Adding the registry in config.yml without port (`url: https://dockerhub.lan`), because its behind a nginx-proxy, results in this error:
`docker-registry-manager    | time="2018-01-18T00:35:27Z" level=fatal msg="Failed to add registry (https://dockerhub.lan), invalid port: strconv.Atoi: parsing \"\": invalid syntax"`

I had to add port 443 to host
`url: https://dockerhub.lan:443`

I think it would be nice to make the port optional and assume the standard SSL port

**Comment by snagles** [comment]
Hi untergrunbiber,

I've made it more obvious that the port is required with a port field in registries.yml file. I'm a fan of making the behavior explicit for which port to use since I run multiple http and https registries on the same hosts with different ports.
