### ISSUE TITLE
Delete image request 

### ISSUE THREAD

**Issue by ruanton29** [snagles/docker-registry-manager#137]
Hi currently using your app it good, but i need so somehow secure it and have some problem with delete button. 
I use upgraded lib nginx_okta_proxy written on ruby ( saml auth ) and all work fine until i try delete image. 
When push delete button it sends POST request with url like 
/registries/docker-registry443/repositories/main/tags/latest/delete and proxy try redirect to this url and i get error 404, ( but only via this simple proxy )  but as i see request path should be 
registries/docker-registry:443/repositories/main/tags ( as i understand ) and it would be cool fi you can help me resolve this problem, or maybe navigate me where i can find solution. 
Best regards
Anton

**Comment by snagles** [comment]
Hi ruanton29,

I have a few questions to help me debug:

- Are you on the latest version of the app?
- Are you adding the registry via the interface or registries.yml?
- Could you provide me with your configuration (removing identifying information)? 
- Are you receiving the 404 from the proxy itself, or from the docker-registry-manager app? 
- Could you provide the relevant nginx log lines in addition to the registry logs (run with debug)?

I've not been able to recreate the missing colon in the delete request in my dev environment. You can try and inspect the href in the browser on the tag name and verify that the registry name is correct there (I would expect it to be for the rest of the app to work).

I've pasted the below snippet of how the delete URL is formed (the :registryName portion is the same through that view, so it should reflect the rest of the page:
```javascript
      // Handle form submission event
      $('#delete-tags').on('submit', function (e) {
        var form = this;

        var x = document.getElementsByClassName("selected");
        $(x).each(function (index) {
          var tagName = $(this).data("tag-name");
          $.ajax({
            type: "POST",
            url: "/registries/{{.registryName}}/repositories/{{.repositoryNameEncode}}/tags/" + tagName + "/delete",
            statusCode: {
            ...
```

**Comment by ruanton29** [comment]
Hi
I hope you don't think that something not working, all working fine =). So before answer all question i just give more info about setup. Currently i need add some auth for docker-ui so scheme look like, 
nginx -> okta_proxy ( https://github.com/dalehamel/okta-auth-proxy i can't find better alternative ) -> docker-registry-manager. If check deeply it's look like this : 
1. Request go through nginx, nginx by default redirect it to  okta_proxy.
2. Okta proxy authenticate me and add header 
```headers "X-Remote-User" => session[:email]
          headers "X-Reproxy-URL" => File.join(url, request.path)
          headers "X-Accel-Redirect" => "/reproxy"
          redirect to('http://localhost') 
```
 and made redirect to localhost ( aka nginx ) with url (request.path) /registries/dockerregistry/repositories/main/somethin/tags. It's ok work fine.
3. When in ui i go to delete image i get at page 404 ( but image deleted if i refresh page a few moment later)  with message `Failure! We were unable to delete latest from the registry. For more details view the `

So i don't blame anyone just try to understand if i can somehow make it more workable =( 
And about your question 
1. Latest
2. Registry.yml
3. https://github.com/dalehamel/okta-auth-proxy ( nginx and okta proxy) 

```
registries:
  myegistry:
    url: https://docker-registry.example.com
    username: user
    password: pass
    port: 443
    refresh-rate: "5m"
    skip-tls-validation: true
```
4. Looks like proxy 
```
2018/02/12 09:13:59 [debug] 10#10: *101 http request line: "POST /registries/doc
ker-registry.example.com:443/repositories/main/something/tags/l
atest/delete HTTP/1.1"
POST /registries/docker-registry.example.com:443/repositories/main/something/tags/latest/delete HTTP/1.1" 404 905 "https://docker-ui.vidible.aolcloud.net/registries/docker-registry.example.com:443/repositories/main/something/tags
```
And chrome debug show me 
```
Request URL:https://docker-ui.example.com/registries/docker-registry.example.com:443/repositories/main/something/tags/latest/delete
404 
Content-Length:0
```
And docker-manager show only in log info about `Failed to retrieve an updated list of tags for `
I don't like saml2 but somehow i need to put it before service =( 
Best regards 
Anton
