### ISSUE TITLE
Cannot delete images

### ISSUE THREAD

**Issue by pavlovpetr** [snagles/docker-registry-manager#144]
Hi,
I cannot delete images from Web interface.
When I try to delete an image I getting the error:  
``` Failure! We were unable to delete nomsmq from the registry. ```
Then I performed  ``` docker logs -f registry ``` and  saw the cause:
` DELETE /v2/windowsbase/manifests/sha256:554b69722f31381f10a2f3ddd81e4cb50beba7af8561e9014a9e431a2c8f825 HTTP/1.1 405 78  `
The 405 error code means that the method "DELETE" of  the curl utility does not allowed.
 
Could you help me?
Thanks, Petr

**Comment by snagles** [comment]
Hi,

Have you enabled deletes on the registry?

https://docs.docker.com/registry/configuration/#delete

**Comment by pavlovpetr** [comment]
Hi,

I relocated the registry to another host and forgot to set up it!
Thank you so much for you tip!
