### ISSUE TITLE
Responsive desing & inspect section

### ISSUE THREAD

**Issue by rdrgporto** [snagles/docker-registry-manager#147]
Hi!

First of all, thanks for creating this repository, it looks nice. Secondly, I am working/testing on your project and I have some doubts:

- It is responsive? That is, **Last Refresh** seems to be outside (I removed ip machine):

<p align="center">
<img src="https://user-images.githubusercontent.com/6654666/37333902-c656de94-26aa-11e8-9517-c1c3292be78b.png" align="center" width="480">
</p>

- On the other hand, **Inspect** section is disabled. It is due to **Docker** config?

<p align="center">
<img src="https://user-images.githubusercontent.com/6654666/37333850-9fc73314-26aa-11e8-8533-b45df252fdba.PNG" align="center" width="480">
</p>

Thanks in advance,

Regards 🖖

**Comment by snagles** [comment]
Hi,

Responsiveness is an active work in progress, I'm actually moving everything to bootstrap 4 currently in branch (https://github.com/snagles/docker-registry-manager/tree/switch-to-bootstrap4) to try to improve on some of this --- I'm not a front end dev by trade :).

As for the inspect, that was a placeholder for hooking into the docker client and displaying some additional details. The "Inspect" tab should probably be removed from the master branch. If you're looking for something finished and polished this project is not quite there yet, but I definitely plan on improving on it.

**Comment by rdrgporto** [comment]
Hi,

Thanks very much for the information 😃,

Regards 🖖
