### ISSUE TITLE
Enable/Disable delete button via config

### ISSUE THREAD

**Issue by jbehrends** [snagles/docker-registry-manager#148]
Is there a way to disable the deletion of images? ie. Remove the delete button via config?
If not, could this be added?

I'd like to use your registry manager as a way for people in my organization to easily browse available images, but not necessarily allow people to easily delete images if possible.

**Comment by snagles** [comment]
Hi,

I'll take a look at this. I was hoping to add user groups/permissions sooner rather than later... but a read only mode may be a reasonable enough stopgap.

**Comment by snagles** [comment]
Added in #175
