### ISSUE TITLE
High usage of CPU

### ISSUE THREAD

**Issue by rdrgporto** [snagles/docker-registry-manager#153]
Hi,

System:

- Ubuntu 16.04
- Docker version 17.12.1-ce
- snagles/docker-registry-manager:latest

I test **Registry Manager** on **Docker**. Example:

```
docker run --detach -v `pwd`/app/registries.yml:/app/registries.yml --name docker-registry-manager -p 8080:8080 -e MANAGER_PORT=8080 -e MANAGER_REGISTRIES=/app/registries.yml -e MANAGER_LOG_LEVEL=warn snagles/docker-registry-manager
```

I realized that there is a high usage of CPU from app process: 

![cpu](https://user-images.githubusercontent.com/6654666/38294635-c7525d4e-37eb-11e8-8e91-652801257408.PNG)

Is it normal this behavior? My actual registry has six repositories only.

Thanks in advance,

Regards 🖖

**Comment by snagles** [comment]
CPU usage shouldn't be that high. Looks to be a bug in switching to a new refresh methodology in the latest push. It should be fixed now. Let me know if you encounter any issues.

**Comment by rdrgporto** [comment]
Thanks 🖖
