### ISSUE TITLE
Enable HTTPS for the Manager not working

### ISSUE THREAD

**Issue by PrimordialKangaroo** [snagles/docker-registry-manager#156]
Trying to get the manager to run on HTTPS. I've added the environmental variables in the docker-compose.yml but I have yet to see it actually listen on HTTPS. I enabled the "admin" port, 8088 and looked at the beego config and it's definitely not set there. I've tried changing the key file name to something different and it's reflected in the beego config. 

```
    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=debug
      - MANAGER_ENABLE_HTTPS=true
      - MANAGER_KEY=/app/test.key
      - MANAGER_CERTIFICATE=/app/server.crt
```

I looked through the main.go and don't actually see anywhere that the `BConfig.Listen.EnableHTTPS` is being set at all. The HTTPSCertFile and KeyFile are being set as well as the HTTPSPort but not EnableHTTPS.

**Comment by snagles** [comment]
Hi,

Looks to have been an oversight. Nice find. It should be fixed in the latest image now.

**Comment by snagles** [comment]
Hi,

Beego defaults to 8080 for http, so it was enabling both HTTP and HTTPS on the same port. I went ahead and disabled http when https is enabled. Give it a try and let me know.

**Comment by PrimordialKangaroo** [comment]
Looks like that fixed it. Thanks you!
