### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by LucasPekel87** [snagles/docker-registry-manager#66]
We have a private registry running and are looking for a manager, this project looks promising, but we can't connect because it's behind authentication.

Would love the ability to connect with out private repository (being authentication)

currently getting the following result:
`Get https://OURREPOSITORYURL:5000/v2/: http: non-successful response (status=401 body="{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":null}]}\n")`

**Comment by snagles** [comment]
Hey Lucas, this should be a minor fix on my end. I've pushed the (untested) changes to add auth on the command line, I'll knock out the rest and test further tonight.

**Comment by snagles** [comment]
This should work now. Add the registry via command line when starting up the app e.g:

Go (could also set in env):
```go build . && ./app --port 8080 --registries http://testuser:testpassword@localhost:5000```

Compose:
```    environment: 
-
 MANAGER_REGISTRIES=http://testuser:testpassword@localhost:5000
```

I've tested with a basic auth registry configured similar to https://github.com/snagles/docker-registry-manager/blob/master/tests/config-test.yml#L26, let me know if you have any problems. Most registries I've dealt with have been on their own networks so TLS/auth wasn't a concern.
