### ISSUE TITLE
Repository is not listing all of the image tags

### ISSUE THREAD

**Issue by parvezakkas** [snagles/docker-registry-manager#78]
I am using the docker image available from docker hub and start up the registry as `docker run -d --name registry-ui -p 8080:8080 snagles/docker-registry-manager`

I then add my private v2 docker registry using the UI. After awhile I can see a list of all the repositories. I browse to a particular repository (i.e. "myRepoName/myImage"). It shows a list of tags for "myImage" but I noticed that it's missing several tags. There are total 45 tags for "myImage" but in the UI, I can only see 39 tags.

All the tags are in the format of `v#-<timestamp>`. Some tags are formatted as "v1.0-GM", "v1.1-GM", "v2.0-GM", etc, all of which are missing except "v3.0-GM-17.2". Also one tag with the timestamp format is missing. So.... not really seeing a pattern and don't see anything in the logs either.

**Comment by parvezakkas** [comment]
Actually, just noticed a lot of errors like this in the log reported from registry.go file in line 97

This is coming up for various repositories/images.

```Get https://myRegistry:443/v2/myRepoName/myImage/blobs/: http: non-successful response (status=404 body="404 page not found

**Comment by snagles** [comment]
Possibly related, for the 45 tags how are you determining that tag count? Are all 45 images valid and have not been deleted? I've seen issues where a delete is issued, the registry removes the digest/manifest links but does not remove it from the catalog (ie the list of tags), in that case I do not show it in the interface.

As for the non successful response, check the registry log (docker logs -f registry) and see if there's any additional information but it seems like there are some malformed blobs in there.

Try running the garbage collector and see if the issues continue to reoccur (https://docs.docker.com/registry/garbage-collection/#example)
