### ISSUE TITLE
Cannot delete images

### ISSUE THREAD

**Issue by parvezakkas** [snagles/docker-registry-manager#79]
I am using the docker image available from docker hub and start up the registry as `docker run -d --name registry-ui -p 8080:8080 snagles/docker-registry-manager`

I then add my private v2 docker registry using the UI. After awhile I can see a list of all the repositories. I browse to a particular repository (i.e. "myRepoName/myImage"). I see a list of tags for "myImage". I select one of the image tag from the list by clicking on the check-box beside it and click the "Delete" button at the bottom of the page. Nothing happens. Don't see any response to my click action.

Browse to "Settings -> Logs" and I see following error, but it's hard to tell if this error is related to the Delete action.

```Failed to retrieve manifest information for https://myRegistry:443```

FYI: The registry is already enabled with delete option and I'm able to delete image tags successfully manually by using registry API and also using a different registry-manager (hyper/docker-registry-web)

**Comment by snagles** [comment]
Any errors in the js console? Sounds like the form is never submitted, double check the registry logs (docker logs -f registry) and see if a request is ever sent

**Comment by parvezakkas** [comment]
Okay. Looks like delete action from the UI is working after-all but it's not intuitive. I tried to see the registry's log but they're too big. So, I gave up on that. But later I noticed what is happening.

1. Ran a dry-run of the garbage collection on the registry. There's nothing available in the registry for clean-up/delete.
2. Used the UI to delete one or more images. At this point, there's no visual response. So, it's hard to tell if anything happened at all.
3. Ran a dry-run of the garbage collection on the registry. Now I see some blobs are marked for deletion.
4. Ran garbage collection and refreshed the UI. Now I see those image tags removed from the list.

So, looks like it's working but it'd be helpful if there are some tweaks. As an end-user, I think the tags/images should be removed if a successful delete command was issued to the registry. Because at this point, even though garbage collection hasn't been run, those images are not available for pulling. Maybe there can be a reminder in the UI to run the garbage-collection.

**Comment by snagles** [comment]
Thanks for the feedback. 

For 2/4 there is a Success/Failure alert box appended to the bottom of the  raised white box (
![capture](https://user-images.githubusercontent.com/9109441/29142627-816ab582-7d20-11e7-8e06-7c47365c7d20.PNG)
), but it is removed after 3 seconds so you don't manually have to close them all. I'll work on making the alerts and the information shown more intuitive/obvious. 

As for the removal of the tags from the list of available images, that is a bug and was not my intention. Seems to have happened when I transitioned from building the table client side to server side (which would reload the whole table, which was slow). I'll address that in the same merge.

I plan on adding some sort of notification system that will notify if blobs are eligible for deletion (current garbage collection is a mess, and have been following issues to request collection as an API endpoint, but I don't believe they've gotten anywhere yet). Your solution of a reminder might be a good stopgap until they reach that point. 

I'll address the logs growing too large/filled with uninformative information in a separate issue.

**Comment by parvezakkas** [comment]
Any chance the new build didn't get pushed to docker hub successfully? I just pulled the latest image but I still don't see that "success" message after hitting the delete button.

I'm also seeing a very weird issue with image deletion. I started noticing that when I delete images using the UI, they do get deleted. But... when I browse the docker registry API to see the existing tags of a repository (i.e. `https://myRegistry:443/v2/namespace/app-name/tags/list`), I still see the tags that were deleted.

**Comment by snagles** [comment]
Docker hub push was successful, its pushed on every merge. Check the JS console and html on deletion and see if the div is hidden, its hard for me to debug your end since I have not been able to recreate the issue.

As for the deleted images, try doing a get request curl -X GET https://myRegistry:443/v2/namespace/app-name/manifests/tag-name or the "deleted" tags and see if the manifest is valid. I expect something like https://github.com/docker/distribution/issues/1816 is happening.
