### ISSUE TITLE
Cannot add a registry with basic auth from Azure Registry service

### ISSUE THREAD

**Issue by drivard** [snagles/docker-registry-manager#87]
Hi,

I cannot seem to manage a registry which is hosted on Azure Containers Registry services.
It is a docker registry running on port 443 and I authenticate it using the MANAGER_REPOSITORIES variable.

		- MANAGER_REGISTRIES='https://username:password@myregistry.azurecr.io:443'
		
I get the error `Failed to parse registry from the passed url.`, but I guess it is related
to the fact that Azure is controlling the password field and that when they generate a
password they use special characters such as `\=%$/` etc.

Would you have an idea how to authenticate using that kind of characters in the basic auth password schema?

Is there a way to escape special characters? 

Regards
Dominick

**Comment by snagles** [comment]
Hey Dominick,

This seems like it would only be an issue with commas or post pound signs, I'll take a look at this tonight and figure out a solution/workaround

**Comment by drivard** [comment]
Thanks, let me know if you need me to test a branch if you come up with a solution.

Dominick

**Comment by snagles** [comment]
Hey Dominick,

Go ahead and give this a try in the develop branch:

- If running from the git checked out dir, add your registry in the config.yml file then ```export MANAGER_REGISTRIES_CONFIG=`pwd`/config.yml ``` then run normal via go run
- If running via docker compose, set the image to develop `image: snagles/docker-registry-manager:develop
` and then uncomment the `MANAGER_REGISTRIES_CONFIG=/opt/config.yml
` line

**Comment by drivard** [comment]
it works fine. Thanks

**Comment by snagles** [comment]
Glad to hear it, I'll clean it up a bit, merge it to master, and then close this out.
