### ISSUE TITLE
Docker password 

### ISSUE THREAD

**Issue by ruanton29** [snagles/docker-registry-manager#94]
Hi I just trying your webui, it really fantastic, but have question. We have secured registry but i need add it like user:pass@registry.com. If there any update which will hide whis?
Thx
Best regards
Anton

**Comment by snagles** [comment]
Hi,

I would add the user/password to the config.yml file then manage "hiding" it via file permissions. The config file will accomplish the same thing as user:pass@registry.com.

Let me know if you have any issues.
